### PR TITLE
Remove Gemfile.lock from repo

### PR DESCRIPTION
**Pull request by adam12**
Best practice seems to be to omit this from the source control.

See this somewhat old post by Yehuda:
http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by seanhandley** [comment]
Thanks @adam12 - that's really interesting and useful to know 👍

**Comment by seanhandley** [comment]
As an aside - I don't maintain this repo any more. I used to use it in a web app in a previous job but now I don't use it at all.

If you want to have commit access then I'm happy to add you to the repo or transfer it over to your username. Let me know what you think.

**Comment by seanhandley** [comment]
Not sure if you'll have received the notification for this message @adam12 ☝️

**Comment by adam12** [comment]
@seanhandley I can take it over. Your choice on adding me to project or transferring it under my namespace.

**Comment by seanhandley** [comment]
Awesome 👍 

I'll transfer it over. All the best!

**Comment by seanhandley** [comment]
It's denying it because you already have a fork with the same name. For now I've just added you as a collaborator but I'm happy to try again if you prefer transfer

**Pull request merged**
